from xrpc_client.client.base import ClientBase
from xrpc_client.namespaces import sync_ns

# TODO(MarshalX): This file should be autogenerated!


class ClientRaw(ClientBase):
    """Group all root namespaces"""

    com: sync_ns.ComNamespace
    bsky: sync_ns.BskyNamespace

    def __init__(self):
        super().__init__()

        self.com = sync_ns.ComNamespace(self)
        self.bsky = sync_ns.BskyNamespace(self)
