name: Publish PyPI Release

on:
  release:
    types: [ created ]

permissions:
  id-token: write
  contents: read

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python.
        uses: actions/setup-python@v6
        with:
          python-version: 3.9

      - name: Load cached Poetry installation.
        id: cached-poetry
        # separate key from the other workflows because of dynamic-versioning plugin
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: poetry-release-${{ runner.os }}-2.2.1  # bump the suffix to reset the cache

      - name: Setup Poetry.
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1

      - name: Add Poetry to PATH.
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install Poetry Plugin.
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build package.
        run: poetry build

      - name: Publish a Python distribution to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
