name: Build and upload package to PyPI

on:
  push:
    branches:
      - pypi
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Poetry.
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python

      - name: Add Poetry to PATH.
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies.
        run: poetry install

      - name: Build package.
        run: poetry build

      - name: Publish a Python distribution to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
