name: Create and Publish release from the version tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Run Cimon (eBPF).
        uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
          prevent: true
          allowed-hosts: >
            files.pythonhosted.org
            install.python-poetry.org
            pypi.org
            upload.pypi.org

      - name: Checkout repository.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release.
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - name: Setup Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Setup Poetry.
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1

      - name: Install Poetry Plugin.
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build package.
        run: poetry build

      - name: Publish a Python distribution to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
