name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.15" ]

    runs-on: ${{matrix.os}}

    env:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v5

      - name: Set up Python.
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation.
        id: cached-poetry
        if: runner.os != 'Windows'
        uses: actions/cache@v5
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-2.2.1  # bump the suffix to reset the cache

      - name: Setup Poetry.
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1

      - name: Add Poetry to PATH.
        if: runner.os != 'Windows'
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Load cached venv.
        id: cached-venv
        # caching the venv stalls for hours on Windows runners
        if: runner.os != 'Windows'
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies.
        if: steps.cached-venv.outputs.cache-hit != 'true'
        run: poetry install --without docs

      - name: Run Tests.
        run: poetry run pytest
